const fs = require('fs');
const path = require('path');

const eu = require('../src/data/research/eu-facilities.json');
const us = require('../src/data/research/us-facilities.json');

// Competitive intel — global immersion deployments
eu.push(
  {
    facility_name: "Submer Barcelona HQ DC",
    operator_company: "Submer",
    country: "ES",
    state_province_region: "Catalonia",
    city: "Barcelona",
    latitude: 41.3874,
    longitude: 2.1686,
    region_priority_bucket: "EU",
    facility_status: "under_construction",
    facility_type: "AI",
    pue_value: null,
    pue_verified: false,
    cooling_type: "immersion",
    liquid_cooling_verified: true,
    immersion_cooling_verified: true,
    cooling_evidence_type: "direct",
    facility_mw: 56,
    mw_verified: true,
    matched_on_pue: false,
    matched_on_cooling: true,
    matched_on_mw: false,
    matched_metric_count: 1,
    qualifies_for_dataset: true,
    liquid_cooling_fit_score: 90,
    confidence_score: 80,
    verification_tier: "strong",
    last_verified_date: "2026-04-03",
    source_1_url: "https://submer.com/",
    source_1_publisher: "Submer",
    opportunity_summary: "Submer's first owned 56MW DC. Barcelona. Immersion at scale. Zero water. COMPETITOR — 400MW+ deployed globally.",
    gpu_architecture: null, gpu_model: null, gpu_count: null, gpu_verified: false,
    gpu_evidence_type: null, compute_vendor: null, rack_density_kw: null,
    notes: "COMPETITOR INTEL. Submer has 400MW+ deployed, 300MW+ in pipeline. $55.5M raised Oct 2024. Customers: Telefonica, ExxonMobil, European Commission, hyperscalers."
  },
  {
    facility_name: "LiquidStack Azerbaijan DC",
    operator_company: "LiquidStack (Bitfury)",
    parent_company: "Bitfury Group",
    country: "AZ",
    state_province_region: "Baku",
    city: "Baku",
    latitude: 40.4093,
    longitude: 49.8671,
    region_priority_bucket: "Other",
    facility_status: "existing",
    facility_type: "HPC",
    pue_value: 1.02,
    pue_verified: true,
    pue_evidence_type: "direct",
    cooling_type: "immersion",
    liquid_cooling_verified: true,
    immersion_cooling_verified: true,
    cooling_evidence_type: "direct",
    facility_mw: 120,
    mw_verified: true,
    matched_on_pue: true,
    matched_on_cooling: true,
    matched_on_mw: false,
    matched_metric_count: 2,
    qualifies_for_dataset: true,
    liquid_cooling_fit_score: 100,
    confidence_score: 85,
    verification_tier: "strong",
    last_verified_date: "2026-04-03",
    source_1_url: "https://liquidstack.com/industries/data-centers",
    source_1_publisher: "LiquidStack",
    opportunity_summary: "120MW — world's largest liquid-cooled DC (2018). PUE 1.02. Two-phase immersion. Hot climate proof. COMPETITOR BENCHMARK.",
    gpu_architecture: null, gpu_model: "Bitfury ASIC (originally crypto)", gpu_count: null, gpu_verified: true,
    gpu_evidence_type: "direct", compute_vendor: "Bitfury", rack_density_kw: 252,
    notes: "COMPETITOR INTEL. World's largest immersion DC. Built by Bitfury, tech became LiquidStack. PUE 1.02 in hot climate."
  },
  {
    facility_name: "LiquidStack Georgia DC",
    operator_company: "LiquidStack (Bitfury)",
    parent_company: "Bitfury Group",
    country: "GE",
    state_province_region: "Tbilisi",
    city: "Tbilisi",
    latitude: 41.7151,
    longitude: 44.8271,
    region_priority_bucket: "Other",
    facility_status: "existing",
    facility_type: "HPC",
    pue_value: 1.03,
    pue_verified: true,
    pue_evidence_type: "direct",
    cooling_type: "immersion",
    liquid_cooling_verified: true,
    immersion_cooling_verified: true,
    cooling_evidence_type: "direct",
    facility_mw: 40,
    mw_verified: true,
    matched_on_pue: true,
    matched_on_cooling: true,
    matched_on_mw: false,
    matched_metric_count: 2,
    qualifies_for_dataset: true,
    liquid_cooling_fit_score: 100,
    confidence_score: 85,
    verification_tier: "strong",
    last_verified_date: "2026-04-03",
    source_1_url: "https://liquidstack.com/industries/data-centers",
    source_1_publisher: "LiquidStack",
    opportunity_summary: "40MW. PUE 1.03. Densest immersion DC at time of build (2015). COMPETITOR BENCHMARK.",
    gpu_architecture: null, gpu_model: "Bitfury ASIC", gpu_count: null, gpu_verified: true,
    gpu_evidence_type: "direct", compute_vendor: "Bitfury", rack_density_kw: 252,
    notes: "COMPETITOR INTEL. First large-scale immersion DC. Republic of Georgia."
  }
);

// GRC TACC deployment (US)
us.push(
  {
    facility_name: "TACC Frontera (GRC Immersion)",
    operator_company: "Texas Advanced Computing Center",
    parent_company: "University of Texas at Austin",
    country: "US",
    state_province_region: "Texas",
    city: "Austin",
    full_address: "Austin, TX",
    latitude: 30.2672,
    longitude: -97.7431,
    region_priority_bucket: "USA",
    facility_status: "existing",
    facility_type: "HPC",
    pue_value: null,
    pue_verified: false,
    cooling_type: "immersion",
    liquid_cooling_verified: true,
    immersion_cooling_verified: true,
    cooling_evidence_type: "direct",
    facility_mw: null,
    mw_verified: false,
    matched_on_pue: false,
    matched_on_cooling: true,
    matched_on_mw: false,
    matched_metric_count: 1,
    qualifies_for_dataset: true,
    liquid_cooling_fit_score: 80,
    confidence_score: 80,
    verification_tier: "strong",
    last_verified_date: "2026-04-03",
    source_1_url: "https://www.grcooling.com/iceraq/",
    source_1_publisher: "GRC",
    opportunity_summary: "GRC ICEraQ immersion cooling Frontera GPU subsystem. 11+ year relationship. COMPETITOR INTEL — GRC's flagship HPC reference.",
    gpu_architecture: "NVIDIA + AMD",
    gpu_model: "Frontera supercomputer GPU subsystem",
    gpu_count: null,
    gpu_verified: true,
    gpu_evidence_type: "direct",
    compute_vendor: "NVIDIA + AMD",
    rack_density_kw: null,
    notes: "COMPETITOR INTEL. GRC's longest customer relationship (11+ years). ICEraQ cools GPU-intensive Frontera subsystem. GRC deployed in 24 countries."
  }
);

fs.writeFileSync(path.join(__dirname, '../src/data/research/eu-facilities.json'), JSON.stringify(eu, null, 2));
fs.writeFileSync(path.join(__dirname, '../src/data/research/us-facilities.json'), JSON.stringify(us, null, 2));
console.log('EU:', eu.length, '| US:', us.length);
