const fs = require('fs');
const path = require('path');

const us = require('../src/data/research/us-facilities.json');

us.push(
  {
    facility_name: "Edged Des Moines",
    operator_company: "Edged Energy",
    parent_company: null,
    country: "US",
    state_province_region: "Iowa",
    city: "Ankeny",
    full_address: "Ankeny, Iowa",
    latitude: 41.7318,
    longitude: -93.6050,
    region_priority_bucket: "USA",
    facility_status: "under_construction",
    facility_type: "AI",
    pue_value: 1.15,
    pue_verified: true,
    pue_evidence_type: "direct",
    cooling_type: "hybrid",
    liquid_cooling_verified: true,
    immersion_cooling_verified: false,
    cooling_evidence_type: "direct",
    facility_mw: 13.2,
    mw_verified: true,
    matched_on_pue: true,
    matched_on_cooling: true,
    matched_on_mw: false,
    matched_metric_count: 2,
    qualifies_for_dataset: true,
    liquid_cooling_fit_score: 85,
    confidence_score: 85,
    verification_tier: "strong",
    last_verified_date: "2026-04-03",
    source_1_url: "https://www.edged.us/news/edged-brings-ultra-efficient-ai-ready-data-center-with-advanced-waterless-cooling-to-des-moines-iowa",
    source_1_publisher: "Edged Energy",
    opportunity_summary: "PUE 1.15. ThermalWorks waterless cooling. 200kW/rack liquid plug-and-play. 13.2MW. Modular design.",
    gpu_architecture: null, gpu_model: null, gpu_count: null, gpu_verified: false,
    gpu_evidence_type: null, compute_vendor: null, rack_density_kw: 200,
    notes: "Edged portfolio-wide PUE 1.15. ThermalWorks waterless system. 70kW air + 200kW liquid per rack."
  },
  {
    facility_name: "Edged Kansas City",
    operator_company: "Edged Energy",
    parent_company: null,
    country: "US",
    state_province_region: "Missouri",
    city: "Kansas City",
    full_address: "Kansas City, MO",
    latitude: 39.0997,
    longitude: -94.5786,
    region_priority_bucket: "USA",
    facility_status: "existing",
    facility_type: "AI",
    pue_value: 1.15,
    pue_verified: true,
    pue_evidence_type: "indirect",
    cooling_type: "hybrid",
    liquid_cooling_verified: true,
    cooling_evidence_type: "direct",
    facility_mw: 26,
    mw_verified: true,
    matched_on_pue: true,
    matched_on_cooling: true,
    matched_on_mw: false,
    matched_metric_count: 2,
    qualifies_for_dataset: true,
    liquid_cooling_fit_score: 80,
    confidence_score: 80,
    verification_tier: "strong",
    last_verified_date: "2026-04-03",
    source_1_url: "https://www.edged.us/",
    source_1_publisher: "Edged Energy",
    opportunity_summary: "PUE 1.15. 26MW. ThermalWorks waterless. 200kW/rack liquid. Nuclear power partnership announced.",
    gpu_architecture: null, gpu_model: null, gpu_count: null, gpu_verified: false,
    gpu_evidence_type: null, compute_vendor: null, rack_density_kw: 200,
    notes: "Nuclear power partnership for long-term clean energy."
  },
  {
    facility_name: "T5 @ Atlanta I",
    operator_company: "T5 Data Centers",
    parent_company: null,
    country: "US",
    state_province_region: "Georgia",
    city: "Atlanta",
    full_address: "Atlanta, GA",
    latitude: 33.7490,
    longitude: -84.3880,
    region_priority_bucket: "USA",
    facility_status: "existing",
    facility_type: "colocation",
    pue_value: null,
    pue_verified: false,
    cooling_type: "hybrid",
    liquid_cooling_verified: true,
    cooling_evidence_type: "direct",
    facility_mw: 7.5,
    mw_verified: true,
    matched_on_pue: false,
    matched_on_cooling: true,
    matched_on_mw: true,
    matched_metric_count: 2,
    qualifies_for_dataset: true,
    liquid_cooling_fit_score: 75,
    confidence_score: 75,
    verification_tier: "strong",
    last_verified_date: "2026-04-03",
    source_1_url: "https://t5datacenters.com/locations/t5-atlanta-i/",
    source_1_publisher: "T5 Data Centers",
    opportunity_summary: "7.5MW with liquid cooling. ≤10MW target. Atlanta market. Air + liquid systems.",
    gpu_architecture: null, gpu_model: null, gpu_count: null, gpu_verified: false,
    gpu_evidence_type: null, compute_vendor: null, rack_density_kw: null,
    notes: "Part of T5 Atlanta campus expanding to 300MW+. ATL I is the small original facility."
  },
  {
    facility_name: "Colovore SJC01 Santa Clara",
    operator_company: "Colovore",
    parent_company: null,
    country: "US",
    state_province_region: "California",
    city: "Santa Clara",
    full_address: "2999 Corvin Drive, Santa Clara, CA",
    latitude: 37.3780,
    longitude: -121.9880,
    region_priority_bucket: "USA",
    facility_status: "existing",
    facility_type: "colocation",
    pue_value: 1.1,
    pue_verified: true,
    pue_evidence_type: "direct",
    cooling_type: "liquid",
    liquid_cooling_verified: true,
    cooling_evidence_type: "direct",
    facility_mw: 4,
    mw_verified: true,
    matched_on_pue: true,
    matched_on_cooling: true,
    matched_on_mw: true,
    matched_metric_count: 3,
    qualifies_for_dataset: true,
    liquid_cooling_fit_score: 100,
    confidence_score: 85,
    verification_tier: "strong",
    last_verified_date: "2026-04-03",
    source_1_url: "https://baxtel.com/data-center/colovore-santa-clara-sjc01",
    source_1_publisher: "Baxtel",
    opportunity_summary: "TRIPLE MATCH: PUE 1.1, wall-to-wall liquid, 4MW. Colovore's original facility. Smaller than SJC02.",
    gpu_architecture: "NVIDIA", gpu_model: "Multi-tenant GPU hosting", gpu_count: null, gpu_verified: false,
    gpu_evidence_type: "indirect", compute_vendor: "NVIDIA", rack_density_kw: 50,
    notes: "Colovore's first facility. Same PUE 1.1 as SJC02 but only 4MW — perfect SOM target."
  }
);

fs.writeFileSync(path.join(__dirname, '../src/data/research/us-facilities.json'), JSON.stringify(us, null, 2));
console.log('US:', us.length);
