const fs = require('fs');
const path = require('path');

const ca = require('../src/data/research/canada-facilities.json');
const us = require('../src/data/research/us-facilities.json');

// New Canadian facilities
ca.push(
  {
    facility_name: "Compass Montreal I",
    operator_company: "Compass Datacenters",
    parent_company: null,
    country: "CA",
    state_province_region: "Quebec",
    city: "Montreal",
    full_address: "8501 Elmslie Street, Montreal, QC",
    latitude: 45.4469,
    longitude: -73.4577,
    region_priority_bucket: "Canada",
    facility_status: "existing",
    facility_type: "colocation",
    customer_type_if_known: "Hyperscale + retail colocation",
    build_phase_if_known: null,
    pue_value: null,
    pue_min_if_range: null,
    pue_max_if_range: 1.17,
    pue_verified: true,
    pue_evidence_type: "direct",
    cooling_type: "hybrid",
    liquid_cooling_verified: true,
    immersion_cooling_verified: false,
    cooling_evidence_type: "direct",
    facility_mw: 9,
    it_load_mw: null,
    total_power_mw: 9,
    mw_verified: true,
    mw_evidence_type: "direct",
    matched_on_pue: true,
    matched_on_cooling: true,
    matched_on_mw: true,
    matched_metric_count: 3,
    qualifies_for_dataset: true,
    liquid_cooling_fit_score: 90,
    immersion_cooling_fit_score: 65,
    small_facility_fit_score: 100,
    opportunity_summary: "TRIPLE MATCH: PUE <1.17, 9MW, Vertiv CoolPhase Flex liquid+air hybrid deploying Q1 2025. KyotoCooling + free cooling 90% of year. 100% Hydro-Quebec renewable.",
    likely_buyer_signal: true,
    ai_hpc_signal: false,
    high_density_signal: true,
    sustainability_signal: true,
    retrofit_vs_newbuild: "newbuild",
    confidence_score: 90,
    confidence_reason: "Compass website + datacenterHawk confirm 9MW, PUE <1.17. Vertiv press release confirms CoolPhase Flex deployment Q1 2025.",
    source_count: 4,
    primary_source_count: 2,
    verification_tier: "strong",
    last_verified_date: "2026-04-03",
    source_1_url: "https://datacenterhawk.com/marketplace/providers/compass-datacenters/8501-elmslie-street/montreal-i",
    source_1_title: "Compass Datacenters Montreal I",
    source_1_publisher: "datacenterHawk",
    source_1_date: null,
    source_1_evidence_snippet: "9MW capacity. KyotoCooling. PUE <1.17.",
    source_2_url: "https://www.vertiv.com/en-emea/about/news-and-insights/news-releases/vertiv-and-compass-datacenters-collaborate-on-combination-liquid-and-air-cooling-system-to-accelerate-deployment-of-liquid-cooling-for-ai-applications/",
    source_2_title: "Vertiv and Compass Datacenters Collaborate on Liquid and Air Cooling System",
    source_2_publisher: "Vertiv",
    source_2_date: "2024-12-01",
    source_2_evidence_snippet: "CoolPhase Flex — first packaged liquid+air cooling integration. Multi-year, multi-billion-dollar supply agreement. Q1 2025 deployment.",
    additional_sources: [],
    gpu_architecture: null,
    gpu_model: null,
    gpu_count: null,
    gpu_verified: false,
    gpu_evidence_type: null,
    compute_vendor: null,
    rack_density_kw: null,
    notes: "IDEAL Solar Steam target: 9MW, PUE <1.17, liquid cooling being deployed. Vertiv CoolPhase Flex partnership."
  },
  {
    facility_name: "Compass Montreal II",
    operator_company: "Compass Datacenters",
    parent_company: null,
    country: "CA",
    state_province_region: "Quebec",
    city: "Montreal",
    full_address: "19701 Clark Graham Avenue, Montreal, QC",
    latitude: 45.4500,
    longitude: -73.4500,
    region_priority_bucket: "Canada",
    facility_status: "existing",
    facility_type: "colocation",
    customer_type_if_known: "Hyperscale",
    build_phase_if_known: "30MW across 9 data halls",
    pue_value: 1.15,
    pue_min_if_range: null,
    pue_max_if_range: null,
    pue_verified: true,
    pue_evidence_type: "direct",
    cooling_type: "hybrid",
    liquid_cooling_verified: true,
    immersion_cooling_verified: false,
    cooling_evidence_type: "direct",
    facility_mw: 30,
    it_load_mw: null,
    total_power_mw: 30,
    mw_verified: true,
    mw_evidence_type: "direct",
    matched_on_pue: true,
    matched_on_cooling: true,
    matched_on_mw: false,
    matched_metric_count: 2,
    qualifies_for_dataset: true,
    liquid_cooling_fit_score: 85,
    immersion_cooling_fit_score: 60,
    small_facility_fit_score: 10,
    opportunity_summary: "PUE as low as 1.15 with KyotoCooling. 30MW across 9 halls. Free cooling 90% of year. Vertiv liquid cooling partnership. 100% renewable.",
    likely_buyer_signal: true,
    ai_hpc_signal: false,
    high_density_signal: true,
    sustainability_signal: true,
    retrofit_vs_newbuild: "newbuild",
    confidence_score: 85,
    confidence_reason: "Baxtel + datacenterHawk confirm 30MW, PUE 1.15. Vertiv partnership confirmed.",
    source_count: 3,
    primary_source_count: 1,
    verification_tier: "strong",
    last_verified_date: "2026-04-03",
    source_1_url: "https://baxtel.com/data-center/compass-montreal-ii",
    source_1_title: "Compass Montreal II Data Center",
    source_1_publisher: "Baxtel",
    source_1_date: null,
    source_1_evidence_snippet: "30MW, 9 data halls, 175k sqft. KyotoCooling, hot aisle containment, PUE as low as 1.15.",
    additional_sources: [],
    gpu_architecture: null, gpu_model: null, gpu_count: null, gpu_verified: false,
    gpu_evidence_type: null, compute_vendor: null, rack_density_kw: null,
    notes: "100% Hydro-Quebec renewable power. Free cooling 90% of year."
  },
  {
    facility_name: "Digital Realty TOR1 Toronto",
    operator_company: "Digital Realty",
    parent_company: "Digital Realty Trust",
    country: "CA",
    state_province_region: "Ontario",
    city: "Vaughan",
    full_address: "1 Century Place, Vaughan, ON",
    latitude: 43.7890,
    longitude: -79.5253,
    region_priority_bucket: "Canada",
    facility_status: "existing",
    facility_type: "colocation",
    pue_value: 1.25,
    pue_verified: true,
    pue_evidence_type: "direct",
    cooling_type: "air",
    liquid_cooling_verified: false,
    cooling_evidence_type: "direct",
    facility_mw: 46,
    mw_verified: true,
    matched_on_pue: false,
    matched_on_cooling: false,
    matched_on_mw: false,
    matched_metric_count: 0,
    qualifies_for_dataset: false,
    liquid_cooling_fit_score: 50,
    confidence_score: 75,
    verification_tier: "strong",
    last_verified_date: "2026-04-03",
    source_1_url: "https://www.digitalrealty.com/data-centers/americas/toronto",
    source_1_publisher: "Digital Realty",
    opportunity_summary: "46MW, PUE 1.25. Air-cooled. No target metrics matched but DLC offering available in 170+ DCs globally.",
    gpu_architecture: null, gpu_model: null, gpu_count: null, gpu_verified: false,
    gpu_evidence_type: null, compute_vendor: null, rack_density_kw: null,
    notes: "PUE 1.25 is outside 1.04-1.20 range. 46MW is above 10MW. Air-cooled. However, Digital Realty offers DLC in 170+ DCs globally — potential future liquid upgrade."
  },
  {
    facility_name: "Equinix TR2 Toronto",
    operator_company: "Equinix",
    parent_company: "Equinix Inc.",
    country: "CA",
    state_province_region: "Ontario",
    city: "Toronto",
    full_address: "45 Parliament Street, Toronto, ON",
    latitude: 43.6511,
    longitude: -79.3594,
    region_priority_bucket: "Canada",
    facility_status: "existing",
    facility_type: "colocation",
    pue_value: null,
    pue_verified: false,
    cooling_type: "air",
    liquid_cooling_verified: false,
    cooling_evidence_type: "direct",
    facility_mw: 16,
    mw_verified: true,
    matched_on_pue: false,
    matched_on_cooling: false,
    matched_on_mw: false,
    matched_metric_count: 0,
    qualifies_for_dataset: false,
    liquid_cooling_fit_score: 45,
    confidence_score: 70,
    verification_tier: "strong",
    last_verified_date: "2026-04-03",
    source_1_url: "https://www.equinix.com/data-centers/americas-colocation/canada-colocation/toronto-data-centers/tr2",
    source_1_publisher: "Equinix",
    opportunity_summary: "16MW, Smardt mag-lev chillers, water-side economizer. No liquid cooling yet. Equinix trialing liquid pods globally — TR2 could be a future deployment.",
    gpu_architecture: null, gpu_model: null, gpu_count: null, gpu_verified: false,
    gpu_evidence_type: null, compute_vendor: null, rack_density_kw: null,
    notes: "Equinix global avg PUE 1.39. TR2 has efficient chillers but no liquid. 16MW — above 10MW target."
  },
  {
    facility_name: "Qu Data Centres Calgary DC3",
    operator_company: "Qu Data Centres",
    parent_company: "Infrared Capital (formerly Rogers)",
    country: "CA",
    state_province_region: "Alberta",
    city: "Airdrie",
    full_address: "34 Highland Park Way NE, Airdrie, AB",
    latitude: 51.2916,
    longitude: -114.0047,
    region_priority_bucket: "Canada",
    facility_status: "existing",
    facility_type: "colocation",
    pue_value: null,
    pue_verified: false,
    cooling_type: "air",
    liquid_cooling_verified: false,
    cooling_evidence_type: null,
    facility_mw: 7.5,
    mw_verified: true,
    matched_on_pue: false,
    matched_on_cooling: false,
    matched_on_mw: true,
    matched_metric_count: 1,
    qualifies_for_dataset: true,
    liquid_cooling_fit_score: 55,
    confidence_score: 60,
    verification_tier: "moderate",
    last_verified_date: "2026-04-03",
    source_1_url: "https://baxtel.com/data-center/rogers-markham-tor-dc3",
    source_1_publisher: "Baxtel",
    opportunity_summary: "7.5MW small colo (former Rogers). ≤10MW = SAM target. No liquid cooling yet — retrofit opportunity. Part of 9-DC portfolio (49MW total).",
    gpu_architecture: null, gpu_model: null, gpu_count: null, gpu_verified: false,
    gpu_evidence_type: null, compute_vendor: null, rack_density_kw: null,
    notes: "Former Rogers facility now operated by Qu Data Centres. 750+ customers across 9 Canadian DCs."
  },
  {
    facility_name: "Beacon AI Foothills Hub",
    operator_company: "Beacon AI Centers",
    parent_company: null,
    country: "CA",
    state_province_region: "Alberta",
    city: "Parkland County",
    full_address: "Parkland County, AB (Keephills-Duffield)",
    latitude: 53.4100,
    longitude: -114.4500,
    region_priority_bucket: "Canada",
    facility_status: "planned",
    facility_type: "AI",
    pue_value: null,
    pue_verified: false,
    cooling_type: "unknown",
    liquid_cooling_verified: false,
    cooling_evidence_type: null,
    facility_mw: 400,
    mw_verified: true,
    matched_on_pue: false,
    matched_on_cooling: false,
    matched_on_mw: false,
    matched_metric_count: 0,
    qualifies_for_dataset: false,
    liquid_cooling_fit_score: 60,
    confidence_score: 65,
    verification_tier: "moderate",
    last_verified_date: "2026-04-03",
    source_1_url: "https://majorprojects.alberta.ca/details/Beacon-Foothills-Artificial-Intelligence-Hub/11490",
    source_1_publisher: "Alberta Major Projects",
    opportunity_summary: "400MW planned AI hub. 4.5GW total Alberta pipeline. Stantec engineering. Construction 2025. Cooling specs not yet disclosed — early opportunity for Solar Steam.",
    gpu_architecture: null, gpu_model: null, gpu_count: null, gpu_verified: false,
    gpu_evidence_type: null, compute_vendor: null, rack_density_kw: null,
    notes: "Massive scale. Cooling not yet specified — potential early engagement opportunity. Alberta Major Projects filing confirmed."
  }
);

// Compute North to US (PUE 1.04!)
us.push(
  {
    facility_name: "Compute North TIER 0",
    operator_company: "Compute North",
    parent_company: null,
    country: "US",
    state_province_region: "Multiple",
    city: "Multiple US locations",
    full_address: null,
    latitude: 44.0,
    longitude: -93.0,
    region_priority_bucket: "USA",
    facility_status: "existing",
    facility_type: "modular",
    pue_value: 1.04,
    pue_verified: true,
    pue_evidence_type: "direct",
    cooling_type: "air",
    liquid_cooling_verified: false,
    cooling_evidence_type: "direct",
    facility_mw: null,
    mw_verified: false,
    matched_on_pue: true,
    matched_on_cooling: false,
    matched_on_mw: false,
    matched_metric_count: 1,
    qualifies_for_dataset: true,
    liquid_cooling_fit_score: 50,
    confidence_score: 70,
    verification_tier: "moderate",
    last_verified_date: "2026-04-03",
    source_1_url: "https://www.computenorth.com/",
    source_1_publisher: "Compute North",
    opportunity_summary: "PUE 1.04 — lowest verified in dataset. TIER 0 facilities. 41% more efficient than Tier 3. Wind/solar/carbon-free energy mix. Originally crypto, pivoting to AI.",
    gpu_architecture: null, gpu_model: null, gpu_count: null, gpu_verified: false,
    gpu_evidence_type: null, compute_vendor: null, rack_density_kw: null,
    notes: "PUE 1.04 is at the very bottom of target range. TIER 0 = purpose-built for efficiency. Air-cooled — remarkable efficiency without liquid. Potential partner or benchmark."
  }
);

fs.writeFileSync(path.join(__dirname, '../src/data/research/canada-facilities.json'), JSON.stringify(ca, null, 2));
fs.writeFileSync(path.join(__dirname, '../src/data/research/us-facilities.json'), JSON.stringify(us, null, 2));
console.log('CA:', ca.length, '| US:', us.length);
