const fs = require('fs');
const path = require('path');

const us = require('../src/data/research/us-facilities.json');
const eu = require('../src/data/research/eu-facilities.json');

// New US facilities from Phase 3 research
us.push(
  {
    facility_name: "Scaleway DC5 Paris",
    operator_company: "Scaleway",
    country: "FR",
    state_province_region: "Ile-de-France",
    city: "Vitry-sur-Seine",
    latitude: 48.7880,
    longitude: 2.3956,
    region_priority_bucket: "EU",
    facility_status: "existing",
    facility_type: "colocation",
    pue_value: 1.15,
    pue_verified: true,
    pue_evidence_type: "direct",
    cooling_type: "air",
    liquid_cooling_verified: false,
    cooling_evidence_type: "direct",
    facility_mw: 20.5,
    mw_verified: true,
    matched_on_pue: true,
    matched_on_cooling: false,
    matched_on_mw: false,
    matched_metric_count: 1,
    qualifies_for_dataset: true,
    liquid_cooling_fit_score: 65,
    confidence_score: 85,
    verification_tier: "strong",
    last_verified_date: "2026-04-03",
    source_1_url: "https://pue.dc5.scaleway.com/en/",
    source_1_publisher: "Scaleway",
    opportunity_summary: "PUE 1.15 at 70% load. 20.5MW. Adiabatic free cooling. Air-cooled — retrofit opportunity for liquid.",
    notes: "Real-time PUE dashboard published. 100% renewable. Retrofit candidate."
  }
);

// Move Scaleway to EU since it's France — remove from US and add to EU
const scaleway = us.pop();
eu.push(scaleway);

// DataBank SLC1 - small facility
us.push(
  {
    facility_name: "DataBank SLC1 Downtown",
    operator_company: "DataBank",
    country: "US",
    state_province_region: "Utah",
    city: "Salt Lake City",
    latitude: 40.7608,
    longitude: -111.8910,
    region_priority_bucket: "USA",
    facility_status: "existing",
    facility_type: "colocation",
    pue_value: null,
    pue_verified: false,
    cooling_type: "hybrid",
    liquid_cooling_verified: true,
    cooling_evidence_type: "indirect",
    facility_mw: 0.5,
    mw_verified: true,
    mw_evidence_type: "direct",
    matched_on_pue: false,
    matched_on_cooling: true,
    matched_on_mw: true,
    matched_metric_count: 2,
    qualifies_for_dataset: true,
    liquid_cooling_fit_score: 70,
    confidence_score: 65,
    verification_tier: "moderate",
    last_verified_date: "2026-04-03",
    source_1_url: "https://www.datacentermap.com/usa/utah/salt-lake-city/databank-slc1/",
    source_1_publisher: "datacentermap.com",
    opportunity_summary: "0.5MW small colo. NVIDIA DGX-Ready certified. Liquid cooling ready.",
    notes: "Very small facility — ideal Solar Steam target size. Part of 6-facility SLC campus (44.8MW total)."
  },
  {
    facility_name: "Flexential Hillsboro 3",
    operator_company: "Flexential",
    country: "US",
    state_province_region: "Oregon",
    city: "Hillsboro",
    latitude: 45.5231,
    longitude: -122.9898,
    region_priority_bucket: "USA",
    facility_status: "existing",
    facility_type: "colocation",
    pue_value: 1.3,
    pue_verified: true,
    pue_evidence_type: "direct",
    cooling_type: "liquid",
    liquid_cooling_verified: true,
    cooling_evidence_type: "direct",
    facility_mw: 36,
    mw_verified: true,
    mw_evidence_type: "direct",
    matched_on_pue: false,
    matched_on_cooling: true,
    matched_on_mw: false,
    matched_metric_count: 1,
    qualifies_for_dataset: true,
    liquid_cooling_fit_score: 75,
    confidence_score: 80,
    verification_tier: "strong",
    last_verified_date: "2026-04-03",
    source_1_url: "https://www.flexential.com/data-centers/or/portland/hillsboro3-data-center",
    source_1_publisher: "Flexential",
    opportunity_summary: "36MW with built-in liquid cooling. PUE 1.3. High-density compute focus.",
    notes: "Flexential Hillsboro campus has 5+ facilities. Hillsboro 5 and 6 also liquid-cooled."
  },
  {
    facility_name: "Sabey SDC Ashburn A",
    operator_company: "Sabey Data Centers",
    country: "US",
    state_province_region: "Virginia",
    city: "Ashburn",
    latitude: 39.0438,
    longitude: -77.4874,
    region_priority_bucket: "USA",
    facility_status: "under_construction",
    facility_type: "colocation",
    pue_value: 1.35,
    pue_verified: true,
    pue_evidence_type: "direct",
    cooling_type: "hybrid",
    liquid_cooling_verified: true,
    cooling_evidence_type: "direct",
    facility_mw: 54,
    mw_verified: true,
    mw_evidence_type: "direct",
    matched_on_pue: false,
    matched_on_cooling: true,
    matched_on_mw: false,
    matched_metric_count: 1,
    qualifies_for_dataset: true,
    liquid_cooling_fit_score: 70,
    confidence_score: 80,
    verification_tier: "strong",
    last_verified_date: "2026-04-03",
    source_1_url: "https://sabeydatacenters.com/locations/ashburn-data-center",
    source_1_publisher: "Sabey Data Centers",
    opportunity_summary: "54MW, 100kW+/rack, liquid-cooled or hybrid. PUE 1.35. Coming online 2026.",
    notes: "38-acre campus, 85MW total. Ashburn Data Center Alley."
  }
);

// LiquidStack reference — competitive intel
eu.push(
  {
    facility_name: "LiquidStack Hong Kong Deployment",
    operator_company: "LiquidStack",
    country: "HK",
    state_province_region: "Hong Kong",
    city: "Hong Kong",
    latitude: 22.3193,
    longitude: 114.1694,
    region_priority_bucket: "Other",
    facility_status: "existing",
    facility_type: "colocation",
    pue_value: 1.01,
    pue_verified: true,
    pue_evidence_type: "direct",
    cooling_type: "immersion",
    liquid_cooling_verified: true,
    immersion_cooling_verified: true,
    cooling_evidence_type: "direct",
    facility_mw: 40,
    mw_verified: true,
    mw_evidence_type: "direct",
    matched_on_pue: true,
    matched_on_cooling: true,
    matched_on_mw: false,
    matched_metric_count: 2,
    qualifies_for_dataset: true,
    liquid_cooling_fit_score: 100,
    confidence_score: 85,
    verification_tier: "strong",
    last_verified_date: "2026-04-03",
    source_1_url: "https://liquidstack.com/videos/immersion-2-rack-platform-pue-1-01",
    source_1_publisher: "LiquidStack",
    opportunity_summary: "PUE 1.01 in hot humid Hong Kong. 40MW IT load. 252kW/rack. Two-phase immersion. Competitive intel — world benchmark.",
    notes: "World record PUE for immersion. Competitor intelligence. NTT and Microsoft have tested LiquidStack."
  },
  {
    facility_name: "DigiPlex Oslo Campus",
    operator_company: "DigiPlex",
    country: "NO",
    state_province_region: "Oslo",
    city: "Oslo",
    latitude: 59.9139,
    longitude: 10.7522,
    region_priority_bucket: "EU",
    facility_status: "existing",
    facility_type: "colocation",
    pue_value: 1.1,
    pue_verified: true,
    pue_evidence_type: "direct",
    cooling_type: "air",
    liquid_cooling_verified: false,
    cooling_evidence_type: "direct",
    facility_mw: null,
    mw_verified: false,
    matched_on_pue: true,
    matched_on_cooling: false,
    matched_on_mw: false,
    matched_metric_count: 1,
    qualifies_for_dataset: true,
    liquid_cooling_fit_score: 60,
    confidence_score: 75,
    verification_tier: "strong",
    last_verified_date: "2026-04-03",
    source_1_url: "https://digiplex.com:443/about-us/cooling/",
    source_1_publisher: "DigiPlex",
    opportunity_summary: "PUE 1.1 via Air-to-Air evaporative cooling. No liquid yet — retrofit opportunity. 65+ MW across 8 Nordic DCs.",
    notes: "Award-winning Air-to-Air system. 25% energy savings vs industry. 100% renewable. Retrofit target for liquid cooling."
  }
);

fs.writeFileSync(path.join(__dirname, '../src/data/research/us-facilities.json'), JSON.stringify(us, null, 2));
fs.writeFileSync(path.join(__dirname, '../src/data/research/eu-facilities.json'), JSON.stringify(eu, null, 2));
console.log('US:', us.length, '| EU:', eu.length);
console.log('Grand total incl CA(10):', us.length + eu.length + 10);
