import json

with open('src/data/facilities/canada.json', encoding='utf-8') as f:
    canada = json.load(f)

existing = {fac['facility_name'].lower() for fac in canada}
max_id = max(int(fac['id'].split('-')[1]) for fac in canada)

new_facilities = [
    # ALBERTA - from agent findings
    {"facility_name": "Crusoe Crossfield Energy Park", "company": "Crusoe / KALiNA Distributed Power", "lat": 51.43, "lng": -114.02, "country": "CA", "region": "Alberta", "city": "Crossfield", "status": "planned", "facility_type": "ai_factory", "capacity_mw": 170, "pue": None, "cooling_method": "unknown", "gpu": "NVIDIA Blackwell", "source": "DCD", "source_url": "https://www.datacenterdynamics.com/en/news/crusoe-kalina-partner-to-develop-natural-gas-powered-ai-data-centers-in-alberta-canada/", "notes": "170MW CCGT with 95% carbon capture. 100k GPUs/building. 15-year PPA."},
    {"facility_name": "Crusoe Alsike Energy Park", "company": "Crusoe / KALiNA Distributed Power", "lat": 51.7, "lng": -113.8, "country": "CA", "region": "Alberta", "city": "Alsike", "status": "planned", "facility_type": "ai_factory", "capacity_mw": 170, "pue": None, "cooling_method": "unknown", "gpu": "NVIDIA Blackwell", "source": "DCD", "source_url": "https://www.datacenterdynamics.com/en/news/crusoe-kalina-partner-to-develop-natural-gas-powered-ai-data-centers-in-alberta-canada/", "notes": "160-acre site between Calgary and Edmonton."},
    {"facility_name": "Crusoe Myers Energy Park", "company": "Crusoe / KALiNA Distributed Power", "lat": 51.8, "lng": -113.6, "country": "CA", "region": "Alberta", "city": "Myers", "status": "planned", "facility_type": "ai_factory", "capacity_mw": 170, "pue": None, "cooling_method": "unknown", "gpu": "NVIDIA Blackwell", "source": "DCD", "source_url": "https://www.datacenterdynamics.com/en/news/crusoe-kalina-partner-to-develop-natural-gas-powered-ai-data-centers-in-alberta-canada/", "notes": "65-acre site. Smallest of 3 Crusoe/KDP Alberta sites."},
    {"facility_name": "Meta / Pembina / Kineticor Greenlight -- Fort Saskatchewan", "company": "Meta Platforms / Pembina Pipeline / Kineticor", "lat": 53.71, "lng": -113.21, "country": "CA", "region": "Alberta", "city": "Fort Saskatchewan", "status": "announced", "facility_type": "hyperscale", "capacity_mw": 1800, "pue": None, "cooling_method": "unknown", "gpu": None, "source": "DCD", "source_url": "https://www.datacenterdynamics.com/en/news/meta-pembina-kineticor-to-collaborate-for-data-center-near-edmonton-canada-report/", "notes": "1864MW CCGT power plant. Meta anchor tenant. Expected 2029."},
    {"facility_name": "Mihta Askiy Data Centre -- Peace River (Indigenous-led)", "company": "Woodland Cree First Nation / Sovereign Digital Infrastructure", "lat": 56.3, "lng": -117.0, "country": "CA", "region": "Alberta", "city": "Peace River", "status": "planned", "facility_type": "ai_factory", "capacity_mw": 650, "pue": None, "cooling_method": "unknown", "gpu": None, "source": "DCD", "source_url": "https://www.datacenterdynamics.com/en/news/woodland-cree-first-nation-to-develop-650mw-data-center-in-alberta-canada/", "notes": "650MW. $1.5B USD. First Indigenous-led DC in Canada. Repurposing Shell Carmon Creek site. 2x200MW Siemens turbines."},
    {"facility_name": "Beacon Langdon AI Hub -- Rocky View County", "company": "Beacon AI Centers", "lat": 51.0, "lng": -113.7, "country": "CA", "region": "Alberta", "city": "Langdon", "status": "planned", "facility_type": "hyperscale", "capacity_mw": 400, "pue": None, "cooling_method": "unknown", "gpu": None, "source": "Alberta Major Projects", "source_url": "https://majorprojects.alberta.ca/details/Beacon-Langdon-Artificial-Intelligence-Hub/11492", "notes": "400MW. 946 acres. $4B investment. Solar farm integrated. ASP approved June 2025."},
    {"facility_name": "Beacon Chestermere Data Centre", "company": "Beacon AI Centers", "lat": 51.03, "lng": -113.82, "country": "CA", "region": "Alberta", "city": "Chestermere", "status": "planned", "facility_type": "hyperscale", "capacity_mw": 400, "pue": None, "cooling_method": "air_cooled", "gpu": None, "source": "City of Chestermere", "source_url": "https://thecityofchestermere.ca/beacon-data-centre/", "notes": "400MW. 310 acres. $4B. Air cooling (water-free claim)."},
    {"facility_name": "Beacon Harry Smith AI Hub -- Parkland County", "company": "Beacon AI Centers", "lat": 53.5, "lng": -114.5, "country": "CA", "region": "Alberta", "city": "Parkland County", "status": "planned", "facility_type": "hyperscale", "capacity_mw": 400, "pue": None, "cooling_method": "unknown", "gpu": None, "source": "Alberta Major Projects", "source_url": "https://majorprojects.alberta.ca/details/Beacon-Hary-Smith-Artificial-Intelligence-Hub/11491", "notes": "400MW. West of Edmonton, between Keephills and Duffield."},
    {"facility_name": "Net Zero Now Energy Campus -- Alberta", "company": "Net Zero Now", "lat": 51.3, "lng": -114.1, "country": "CA", "region": "Alberta", "city": "Alberta", "status": "planned", "facility_type": "hyperscale", "capacity_mw": 400, "pue": None, "cooling_method": "unknown", "gpu": None, "source": "PR Newswire", "source_url": "https://www.prnewswire.com/news-releases/net-zero-now-clears-key-milestone-on-320-acre-energy-campus-accelerating-albertas-low-carbon-data-center-infrastructure-build-out-302500099.html", "notes": "320 acres. Wind/solar + batteries + natural gas. AUC approval pending."},
    {"facility_name": "Wonder Valley AI Data Centre Park -- Grande Prairie", "company": "O'Leary Ventures / O'Leary Digital", "lat": 55.17, "lng": -118.8, "country": "CA", "region": "Alberta", "city": "Grande Prairie", "status": "planned", "facility_type": "hyperscale", "capacity_mw": 1400, "pue": None, "cooling_method": "unknown", "gpu": None, "source": "Alberta Major Projects", "source_url": "https://majorprojects.alberta.ca/details/Wonder-Valley-AI-Data-Centre-Park/11477", "notes": "Phase 1 1.4GW, total 7.5GW. 2000+ acres on Montney gas deposit. $70B+ total. Kevin O'Leary-backed."},
    {"facility_name": "Whipcord Edge LDC01 -- Lethbridge", "company": "Whipcord Edge Data Centers", "lat": 49.72, "lng": -112.78, "country": "CA", "region": "Alberta", "city": "Lethbridge", "status": "operational", "facility_type": "colocation", "capacity_mw": 1.5, "pue": None, "cooling_method": "air_cooled", "gpu": None, "source": "Baxtel", "source_url": "https://baxtel.com/data-center/whipcord-edge-lethbridge", "notes": "7500 sqft. 2.5MW feed expandable to 5MW."},
    {"facility_name": "Hut 8 Medicine Hat", "company": "Hut 8 Mining Corp", "lat": 50.04, "lng": -110.68, "country": "CA", "region": "Alberta", "city": "Medicine Hat", "status": "operational", "facility_type": "enterprise", "capacity_mw": 67, "pue": None, "cooling_method": "air_cooled", "gpu": None, "source": "Baxtel", "source_url": "https://baxtel.com/data-center/hut-8-medicine-hat-alberta", "notes": "85 BlockBox containers. Currently shut down but lease maintained."},
    {"facility_name": "Equinix Calgary CL2", "company": "Equinix", "lat": 51.06, "lng": -114.02, "country": "CA", "region": "Alberta", "city": "Calgary", "status": "operational", "facility_type": "colocation", "capacity_mw": None, "pue": None, "cooling_method": "air_cooled", "gpu": "NVIDIA DGX-Ready", "source": "Equinix", "source_url": "https://www.equinix.com/data-centers/americas-colocation/canada-colocation/calgary-data-centers/cl2", "notes": "1930 Maynard Road SE. DR/product solutions focus."},
    {"facility_name": "DataHiveTwo -- Calgary", "company": "DataHive Group", "lat": 51.05, "lng": -114.07, "country": "CA", "region": "Alberta", "city": "Calgary", "status": "operational", "facility_type": "colocation", "capacity_mw": None, "pue": None, "cooling_method": "air_cooled", "gpu": None, "source": "DataHive", "source_url": "https://datahive.ca/datahivetwo/", "notes": "801 7th Ave SW Nexen Building. 9000 sqft DC + 13000 sqft office. Opened 2024."},
    {"facility_name": "AWS Canada West (Calgary Region)", "company": "Amazon Web Services", "lat": 51.1, "lng": -114.1, "country": "CA", "region": "Alberta", "city": "Calgary", "status": "operational", "facility_type": "hyperscale", "capacity_mw": None, "pue": None, "cooling_method": "unknown", "gpu": None, "source": "AWS", "source_url": "https://aws.amazon.com/blogs/aws/the-aws-canada-west-calgary-region-is-now-available/", "notes": "ca-west-1. 3 AZs. $4B CAD investment through 2037. Launched Dec 2023."},
    {"facility_name": "Qu Data Centres EDM1 Edmonton", "company": "Qu Data Centres (InfraRed)", "lat": 53.54, "lng": -113.51, "country": "CA", "region": "Alberta", "city": "Edmonton", "status": "operational", "facility_type": "colocation", "capacity_mw": 4, "pue": None, "cooling_method": "air_cooled", "gpu": None, "source": "datacentermap.com", "source_url": "https://www.datacentermap.com/canada/edmonton/rogers-edmonton-1/", "notes": "10200 102 Ave NW. Tier III. Formerly Rogers EDM DC1."},
    {"facility_name": "Five Nine Data Center Edmonton", "company": "Five Nine Data Center", "lat": 53.57, "lng": -113.47, "country": "CA", "region": "Alberta", "city": "Edmonton", "status": "operational", "facility_type": "colocation", "capacity_mw": None, "pue": None, "cooling_method": "unknown", "gpu": None, "source": "Five Nine DC", "source_url": "https://www.5-9dc.com/facility", "notes": "17008 90 St NW. 28000 sqft. Hydrogen-powered. Seismically stable."},
    # ONTARIO - major additions from agent
    {"facility_name": "Cologix TOR1 -- 151 Front Street", "company": "Cologix", "lat": 43.64, "lng": -79.38, "country": "CA", "region": "Ontario", "city": "Toronto", "status": "operational", "facility_type": "colocation", "capacity_mw": 20, "pue": None, "cooling_method": "air_cooled", "gpu": None, "source": "Cologix", "source_url": "https://cologix.com/data-centers/toronto/tor1/", "notes": "7 data centres at 151 Front St W. Canada largest carrier hotel. 150+ networks."},
    {"facility_name": "Digital Realty TOR1 Vaughan -- 1 Century Place", "company": "Digital Realty", "lat": 43.82, "lng": -79.53, "country": "CA", "region": "Ontario", "city": "Vaughan", "status": "operational", "facility_type": "hyperscale", "capacity_mw": 50, "pue": None, "cooling_method": "air_cooled", "gpu": None, "source": "Digital Realty", "source_url": "https://www.digitalrealty.com/data-centers/americas/toronto/tor1", "notes": "711000 sqft. LEED Silver. 23 computer rooms. Largest in Toronto metro."},
    {"facility_name": "Urbacon DC7 Etobicoke", "company": "Urbacon Data Centre Solutions", "lat": 43.67, "lng": -79.56, "country": "CA", "region": "Ontario", "city": "Etobicoke", "status": "operational", "facility_type": "colocation", "capacity_mw": 22, "pue": None, "cooling_method": "unknown", "gpu": None, "source": "datacentermap.com", "source_url": "https://www.datacentermap.com/canada/toronto/urbacon-dc-toronto-dc7/", "notes": "310 Humberline Dr."},
    {"facility_name": "STACK TOR01 Campus -- 56MW Toronto", "company": "STACK Infrastructure", "lat": 43.69, "lng": -79.29, "country": "CA", "region": "Ontario", "city": "Toronto", "status": "operational", "facility_type": "colocation", "capacity_mw": 56, "pue": None, "cooling_method": "air_cooled", "gpu": None, "source": "STACK Infrastructure", "source_url": "https://www.stackinfra.com/locations/americas/toronto/tor01/", "notes": "3650 Danforth Ave. 19-acre site. 56MW total (8MW Phase 1, 24MW Phase 2, 24MW Phase 3). 100% renewable."},
    {"facility_name": "Compass Datacenters North York YYZ2", "company": "Compass Datacenters", "lat": 43.77, "lng": -79.47, "country": "CA", "region": "Ontario", "city": "North York", "status": "operational", "facility_type": "colocation", "capacity_mw": 30, "pue": None, "cooling_method": "unknown", "gpu": None, "source": "Compass Datacenters", "source_url": "https://www.compassdatacenters.com/news/compass-datacenters-acquires-new-toronto-campus/", "notes": "15 Fenmar Drive. 300000 sqft. Phase 1: 10MW."},
    {"facility_name": "Telehouse 151 Front Street Toronto -- Deep Lake Water Cooling", "company": "Telehouse Canada", "lat": 43.64, "lng": -79.38, "country": "CA", "region": "Ontario", "city": "Toronto", "status": "operational", "facility_type": "colocation", "capacity_mw": 20, "pue": None, "cooling_method": "liquid_cooled", "gpu": None, "source": "Telehouse", "source_url": "https://www.telehouse.ca/data-centres/", "notes": "205000 sqft. Deep Lake Water Cooling System. 100% renewable energy."},
    {"facility_name": "Qu Data Centres LON DC1 London", "company": "Qu Data Centres (InfraRed)", "lat": 42.97, "lng": -81.24, "country": "CA", "region": "Ontario", "city": "London", "status": "operational", "facility_type": "colocation", "capacity_mw": 30, "pue": None, "cooling_method": "unknown", "gpu": None, "source": "datacentermap.com", "source_url": "https://www.datacentermap.com/canada/london-on/rogers-london-1/", "notes": "970 Green Valley Road. Formerly Rogers."},
    {"facility_name": "Microsoft Etobicoke -- Rexdale", "company": "Microsoft Azure", "lat": 43.72, "lng": -79.57, "country": "CA", "region": "Ontario", "city": "Etobicoke", "status": "under_construction", "facility_type": "hyperscale", "capacity_mw": None, "pue": None, "cooling_method": "unknown", "gpu": None, "source": "DCD", "source_url": "https://www.datacenterdynamics.com/en/news/microsoft-planning-toronto-data-center-on-site-of-closed-lowes-store/", "notes": "289450 sqft. 2-storey. Former Lowe's site."},
    # QUEBEC - major additions
    {"facility_name": "OVHcloud BHS Campus Beauharnois -- 120MW", "company": "OVHcloud", "lat": 45.31, "lng": -73.87, "country": "CA", "region": "Quebec", "city": "Beauharnois", "status": "operational", "facility_type": "hyperscale", "capacity_mw": 120, "pue": 1.09, "cooling_method": "liquid_cooled", "gpu": "NVIDIA H100", "source": "OVHcloud", "source_url": "https://corporate.ovhcloud.com/en/newsroom/news/watercooling-anniversary/", "notes": "4 buildings (BHS1-BHS5). PUE 1.09. Server water cooling (proprietary). Former Rio Tinto Alcan plant. Adjacent to 1903MW Beauharnois dam."},
    {"facility_name": "Compass Montreal I -- KyotoCooling", "company": "Compass Datacenters", "lat": 45.43, "lng": -73.63, "country": "CA", "region": "Quebec", "city": "LaSalle", "status": "operational", "facility_type": "colocation", "capacity_mw": 9, "pue": 1.17, "cooling_method": "air_cooled", "gpu": None, "source": "Compass", "source_url": "https://www.compassdatacenters.com/locations/montreal-data-centers/", "notes": "9MW expandable to 65MW. PUE <1.17. KyotoCooling."},
    {"facility_name": "Compass Montreal II -- Baie-d'Urfe", "company": "Compass Datacenters", "lat": 45.41, "lng": -73.89, "country": "CA", "region": "Quebec", "city": "Baie-d'Urfe", "status": "operational", "facility_type": "colocation", "capacity_mw": 20, "pue": 1.15, "cooling_method": "air_cooled", "gpu": None, "source": "Baxtel", "source_url": "https://baxtel.com/data-center/compass-montreal-ii", "notes": "20MW expandable to 50MW. PUE 1.15. KyotoCooling + hot aisle containment."},
    {"facility_name": "Microsoft Quebec City -- L'Ancienne-Lorette", "company": "Microsoft Azure", "lat": 46.79, "lng": -71.35, "country": "CA", "region": "Quebec", "city": "L'Ancienne-Lorette", "status": "under_construction", "facility_type": "hyperscale", "capacity_mw": 90, "pue": None, "cooling_method": "unknown", "gpu": None, "source": "DCD", "source_url": "https://www.datacenterdynamics.com/en/news/microsoft-breaks-ground-on-data-center-in-quebec-city-canada/", "notes": "~90MW. Part of $680M+ USD Microsoft Quebec investment. Early 2026 target."},
    {"facility_name": "Nordik Data Centers NDC1 Shawinigan", "company": "Nordik Data Centers", "lat": 46.55, "lng": -72.75, "country": "CA", "region": "Quebec", "city": "Shawinigan", "status": "operational", "facility_type": "ai_factory", "capacity_mw": 5, "pue": None, "cooling_method": "liquid_cooled", "gpu": None, "source": "DCD", "source_url": "https://www.datacenterdynamics.com/en/news/nordik-dc-partners-with-accelsius-for-data-center-in-montreal-canada/", "notes": "46000 sqft. Accelsius NeuCool direct-to-chip cooling. 2M+ sqft development land."},
    {"facility_name": "TELUS Sovereign AI Factory -- Rimouski", "company": "TELUS", "lat": 48.45, "lng": -68.52, "country": "CA", "region": "Quebec", "city": "Rimouski", "status": "operational", "facility_type": "ai_factory", "capacity_mw": 2.7, "pue": 1.15, "cooling_method": "air_cooled", "gpu": "NVIDIA Hopper", "source": "TELUS", "source_url": "https://www.telus.com/en/about/news-and-events/media-releases/telus-opens-canadas-first-fully-sovereign-ai-factory", "notes": "Phase 1 2.7MW, 16MW at full build. PUE 1.15-1.18. 500 Hopper GPUs. Blackwell planned."},
    # ATLANTIC - major additions
    {"facility_name": "HIVE Digital Cloud Plaza -- Grand Falls NB", "company": "HIVE Digital Technologies", "lat": 47.05, "lng": -67.74, "country": "CA", "region": "New Brunswick", "city": "Grand Falls", "status": "operational", "facility_type": "ai_factory", "capacity_mw": 70, "pue": 1.3, "cooling_method": "unknown", "gpu": None, "source": "HIVE Digital", "source_url": "https://www.hivedigitaltechnologies.com/news/hive-digital-technologies-accelerates-into-the-ai-super-cycle-by-securing-prime-land-for-next-gen-tier-iii-ai-hpc-data-centers-and-surpassing-23-ehs/", "notes": "80MW substation. Currently Bitcoin mining. Planning Tier III+ AI conversion for 25-30k GPUs. Hydro-powered."},
    {"facility_name": "Equinix SJ1 Saint John", "company": "Equinix", "lat": 45.27, "lng": -66.06, "country": "CA", "region": "New Brunswick", "city": "Saint John", "status": "operational", "facility_type": "colocation", "capacity_mw": 3, "pue": None, "cooling_method": "unknown", "gpu": "NVIDIA DGX-Ready", "source": "Equinix", "source_url": "https://www.equinix.com/data-centers/americas-colocation/canada-colocation/saint-john-data-centers/sj1", "notes": "7 McIntosh Street. 16000 sqft. Trans-Atlantic connectivity. 1hr from US border."},
    {"facility_name": "Fibre Centre Moncton", "company": "Fibre Centre Ltd", "lat": 46.1, "lng": -64.77, "country": "CA", "region": "New Brunswick", "city": "Moncton", "status": "operational", "facility_type": "colocation", "capacity_mw": 2, "pue": None, "cooling_method": "hybrid", "gpu": None, "source": "Fibre Centre", "source_url": "https://fibrecentre.com/", "notes": "770 St George Blvd. 25000 sqft. Infra supports 30MW. 22 Tier 1-4 carriers. MonctonIX host."},
    {"facility_name": "Eastlink Pennant Point -- Halifax", "company": "Eastlink", "lat": 44.47, "lng": -63.58, "country": "CA", "region": "Nova Scotia", "city": "Sambro", "status": "operational", "facility_type": "colocation", "capacity_mw": None, "pue": None, "cooling_method": "air_cooled", "gpu": None, "source": "Eastlink", "source_url": "https://www.newswire.ca/news-releases/eastlink-chooses-nova-scotia-for-2nd-data-centre-513579961.html", "notes": "233 Sambro Creek Road. 13000 sqft on 30 acres. Tier III. $20M investment."},
]

zone_map = {
    "Alberta": "ca-ab",
    "British Columbia": "ca-bc",
    "Ontario": "ca-on",
    "Quebec": "ca-qc",
    "Saskatchewan": "ca-federal",
    "Manitoba": "ca-federal",
    "New Brunswick": "ca-federal",
    "Nova Scotia": "ca-federal",
}

added = 0
skipped = 0
for fac in new_facilities:
    if fac['facility_name'].lower() in existing:
        print(f"SKIP: {fac['facility_name']}")
        skipped += 1
        continue
    max_id += 1
    fac['id'] = f'ca-{max_id:03d}'
    fac['regulatory_zone'] = zone_map.get(fac['region'], 'ca-federal')
    fac['address'] = f"{fac['city']}, {fac['region']}, Canada"
    fac['confidence_tier'] = 'verified'
    fac['source_date'] = '2026-04'
    fac['last_verified'] = '2026-04-06'
    fac['data_gaps'] = [k for k in ['pue', 'capacity_mw', 'gpu'] if fac.get(k) is None]
    canada.append(fac)
    existing.add(fac['facility_name'].lower())
    added += 1
    print(f"ADDED: {fac['id']} | {fac['facility_name']} | {fac['region']} | {fac.get('capacity_mw')}MW | {fac['status']}")

with open('src/data/facilities/canada.json', 'w', encoding='utf-8') as f:
    json.dump(canada, f, indent=2, ensure_ascii=False)

print(f"\nAdded: {added} | Skipped: {skipped} | Total Canada: {len(canada)}")
